// <auto-generated />
namespace İzin_Application.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateetme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateetme));
        
        string IMigrationMetadata.Id
        {
            get { return "202312302000314_updateetme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
